# Generated by Django 5.0 on 2023-12-07 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('journal_name', models.CharField(blank=True, max_length=255)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('number_of_co_authors', models.PositiveIntegerField(default=0)),
                ('number_of_co_authors_from_organization', models.PositiveIntegerField(default=0)),
                ('link_to_resource', models.URLField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researchers', models.ManyToManyField(related_name='articles', to='achievements.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.researcher')),
            ],
        ),
    ]
